ERROR:root:An error occurred in create_filter: 'dict' object has no attribute 'id'
ERROR:root:An error occurred in create_filter: 'bool' object has no attribute 'id'
ERROR:root:An error occurred in create_filter: 'bool' object has no attribute 'id'
INFO:werkzeug:127.0.0.1 - - [10/Nov/2023 01:02:17] "POST /api/landing/command/create_filter_data HTTP/1.1" 200 -
ERROR:root:An error occurred in create_filter: 'dict' object has no attribute 'id'
ERROR:root:An error occurred in create_filter: 'bool' object has no attribute 'id'
