ERROR:root:An error occurred in get_advertisement_by_filter_id_and_value: 'dict' object has no attribute 'header_id'
INFO:werkzeug:127.0.0.1 - - [20/Dec/2023 15:39:16] "GET /api/advertisement/quary/get_advertisement_by_filter?filter_id=1&value=Some%20value HTTP/1.1" 200 -
ERROR:root:An error occurred in get_advertisement_by_filter_id_and_value: 'dict' object has no attribute 'header_id'
